[package]
name = "smb-core"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = "1.3.0"
serde = { version = "1.0.144", features = ["derive"] }
num_enum = "0.5.7"